### ISSUE TITLE
How can multiple tuning parameters be specified?

### ISSUE THREAD

**Issue by bschonec** [robertdebock/ansible-role-sysctl#1]
It looks to me like you need to envoke the role for every tuning parameter you want changed.  This doesn't seem right to me.  What it the syntax for pushing multiple parameters at once?  I tried this:

sysctl_items:
  name: vm.swappiness
  value: 10
  name: vm.dirty_ratio
  value: 15
  name: vm.dirty_background_ratio
  value: 3 
  name: vm.dirty_writeback_centisecs
  value: 100
  name: vm.dirty_expire_centisecs
  value: 500

But of course only the last "name:" is accepted.

**Comment by robertdebock** [comment]
Sorry, missed your question here.

The documentation shows that `sysctl_items` is a list. You can set multiple items like this:

```yaml
---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.sysctl
      sysctl_items:
        - name: vm.swappiness
          value: 10
        - name: vm.dirty_ratio
          value: 15
        - name: vm.dirty_background_ratio
          value: 3
        - name: vm.dirty_writeback_centisecs
          value: 100
        - name: vm.dirty_expire_centisecs
          value: 500
```

Hope this helps!
